apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80  # External port (e.g., for LoadBalancer)
      targetPort: 3002  # Matches the containerPort in deployment.yaml
  type: LoadBalancer  # Use ClusterIP or NodePort if needed
