pipeline:
  name: Demo-Cd
  identifier: DemoCd
  projectIdentifier: HarnessTaskNew
  orgIdentifier: default
  stages:
    - stage:
        description: ""
        failureStrategies:
          - onFailure:
              action:
                type: StageRollback
              errors:
                - AllErrors
        identifier: deploy_node_app
        name: deploy-node-app
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: Productioncd
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: productionwin
          execution:
            rollbackSteps:
              - step:
                  identifier: rollbackCanaryDelete
                  name: Canary Delete
                  spec: {}
                  timeout: 10m
                  type: K8sCanaryDelete
              - step:
                  identifier: rollingRollback
                  name: Rolling Rollback
                  spec: {}
                  timeout: 10m
                  type: K8sRollingRollback
            steps:
              - stepGroup:
                  identifier: canaryDeployment
                  name: Canary Deployment
                  steps:
                    - step:
                        identifier: canaryDeployment
                        name: Canary Deployment
                        spec:
                          instanceSelection:
                            spec:
                              count: 1
                            type: Count
                          skipDryRun: false
                          manifests:
                            - manifest:
                                identifier: deployment
                                type: K8sManifest
                                spec:
                                  store:
                                    type: Git
                                    spec:
                                      connectorRef: account.Github
                                      gitFetchType: Branch
                                      paths:
                                        - k8s/deployment.yaml
                                      branch: main
                            - manifest:
                                identifier: service
                                type: K8sManifest
                                spec:
                                  store:
                                    type: Git
                                    spec:
                                      connectorRef: account.Github
                                      gitFetchType: Branch
                                      paths:
                                        - k8s/service.yaml
                                      branch: main
                        timeout: 10m
                        type: K8sCanaryDeploy
                    - step:
                        identifier: canaryDelete
                        name: Canary Delete
                        spec: {}
                        timeout: 10m
                        type: K8sCanaryDelete
              - stepGroup:
                  identifier: primaryDeployment
                  name: Primary Deployment
                  steps:
                    - step:
                        identifier: rollingDeployment
                        name: Rolling Deployment
                        spec:
                          skipDryRun: false
                          manifests:
                            - manifest:
                                identifier: deployment
                                type: K8sManifest
                                spec:
                                  store:
                                    type: Git
                                    spec:
                                      connectorRef: account.Github
                                      gitFetchType: Branch
                                      paths:
                                        - k8s/deployment.yaml
                                      branch: main
                            - manifest:
                                identifier: service
                                type: K8sManifest
                                spec:
                                  store:
                                    type: Git
                                    spec:
                                      connectorRef: account.Github
                                      gitFetchType: Branch
                                      paths:
                                        - k8s/service.yaml
                                      branch: main
                        timeout: 10m
                        type: K8sRollingDeploy
          service:
            serviceRef: nodeappservice
        tags: {}
        type: Deployment
        delegateSelectors:
          - helm-delegate-win
  tags: {}
