pipeline:
  name: Build Test-Node-HK007
  identifier: Build_harigithub_Test_Node_HK007_1759453381776
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: npm test
                  identifier: npm_test
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm run build --if-present
                      npm test
                    connectorRef: MyDockerHubRegistryConnector
                    image: node:18
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: MyDockerHubRegistryConnector
                    repo: haridockerhub007/harness-node-test
                    tags:
                      - <+pipeline.sequenceId>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: MyMinikubeHarnessConnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        infrastructure:
          type: KubernetesDirect
          spec:
            connectorRef: MyMinikubeHarnessConnector
            namespace: harness-delegate-ng
            automountServiceAccountToken: true
            nodeSelector: {}
            os: Linux
        delegateSelectors:
          - helm-delegate
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: harigithub/Test-Node-HK007
        build: <+input>
