pipeline:
  name: Build Test-Node-HK007
  identifier: Build_harigithub_Test_Node_HK007_1759453381776
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run
                  identifier: Run
                  spec:
                    connectorRef: MyDockerHubRegistryConnector
                    image: haridockerhub007/harness-node-test
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      node --version
                      npm install
                      npm run build --if-present
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: MyMinikubeHarnessConnector
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: harigithub/Test-Node-HK007
        build: <+input>
