pipeline:
  identifier: Build_harigithub_Test_Node_HK007_1759456783493
  name: "CI Node-App "
  orgIdentifier: default
  projectIdentifier: HarnessTaskNew
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: harigithub/Test-Node-HK007
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github
                    repoName: harigithub/Test-Node-HK007.git
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: npm test
                  identifier: npm_test
                  spec:
                    connectorRef: MyDockerRegistry
                    image: node:20.19
                    shell: Sh
                    command: |-
                      npm install
                      npm run build --if-present
                      npm test
                    resources:
                      limits:
                        memory: 512Mi
                        cpu: "0.5"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: MyDockerRegistry
                    repo: haridockerhub007/harness-node-test
                    tags:
                      - <+pipeline.sequenceId>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: MyKubeConnectorNew
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  tags: {}
