infrastructureDefinition:
  name: production-infra
  identifier: productionwin
  orgIdentifier: default
  projectIdentifier: HarnessTaskNew
  environmentRef: Productioncd
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: k8swin
    namespace: harness-delegate-ng
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: false
